services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/form_db
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=your_email@example.com
      - EMAIL_HOST_PASSWORD=your_password
      - ADMIN_EMAIL=admin@example.com

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: form_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
